### ISSUE TITLE
Could not pass event PlayerInteractEvent to Deadbolt v2.2 (latest dev build)

### ISSUE THREAD

**Issue by andris155** [md-5/Deadbolt#119]
[16:29:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Deadbolt v2.2
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:762) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_51]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:772) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614) [spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.util.UnknownFormatConversionException: Conversion = 'l'
    at java.util.Formatter$FormatSpecifier.conversion(Unknown Source) ~[?:1.8.0_51]
    at java.util.Formatter$FormatSpecifier.<init>(Unknown Source) ~[?:1.8.0_51]
    at java.util.Formatter.parse(Unknown Source) ~[?:1.8.0_51]
    at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_51]
    at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_51]
    at java.lang.String.format(Unknown Source) ~[?:1.8.0_51]
    at com.daemitus.deadbolt.Config.sendBroadcast(Config.java:110) ~[?:?]
    at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteractContainer(PlayerListener.java:251) ~[?:?]
    at com.daemitus.deadbolt.events.PlayerListener.handleRightClick(PlayerListener.java:68) ~[?:?]
    at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteract(PlayerListener.java:32) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.jar:git-PaperSpigot-d709888-18fbb24]
    ... 17 more

**Comment by andris155** [comment]
Fixed:
Translation error.
