### ISSUE TITLE
Could not pass event PLAYER_INTERACT

### ISSUE THREAD

**Issue by lucasdidur** [md-5/Deadbolt#24]
2011-12-14 15:54:33 [SEVERE] Could not pass event PLAYER_INTERACT to Deadbolt
java.lang.ClassCastException: org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
    at com.daemitus.deadbolt.events.PlayerListener.placeSign(PlayerListener.java:173)
    at com.daemitus.deadbolt.events.PlayerListener.handleRightClick(PlayerListener.java:67)
    at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteract(PlayerListener.java:45)
    at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:335)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:266)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
    at net.minecraft.server.Packet15Place.a(SourceFile:39)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-14 15:54:33 [SEVERE] Could not pass event REDSTONE_CHANGE to Deadbolt
java.lang.NullPointerException

**Comment by daemitus** [comment]
Pretty sure I fixed this with the last build, ill post it in a bit once Ive got a moment.

**Comment by daemitus** [comment]
Find it again, and we'll stomp it.
