### ISSUE TITLE
error 2.0.6

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#31]
01:00:22 [SEVERE] Could not pass event PLAYER_INTERACT to Deadbolt
java.lang.NullPointerException
        at com.daemitus.deadbolt.Deadbolted.parseSignAttached(Deadbolted.java:250)
        at com.daemitus.deadbolt.Deadbolted.parseNearbySigns(Deadbolted.java:245)
        at com.daemitus.deadbolt.Deadbolted.searchFenceGate(Deadbolted.java:140)
        at com.daemitus.deadbolt.Deadbolted.search(Deadbolted.java:57)
        at com.daemitus.deadbolt.Deadbolted.<init>(Deadbolted.java:38)
        at com.daemitus.deadbolt.Deadbolted.get(Deadbolted.java:34)
        at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteractDoor(PlayerListener.java:181)
        at com.daemitus.deadbolt.events.PlayerListener.handleRightClick(PlayerListener.java:68)
        at com.daemitus.deadbolt.events.PlayerListener.onPlayerInteract(PlayerListener.java:40)
        at org.bukkit.plugin.java.JavaPluginLoader$11.execute(JavaPluginLoader.java:335)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:178)
        at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:266)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:593)
        at net.minecraft.server.Packet15Place.a(SourceFile:39)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:550)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by daemitus** [comment]
Sonofa bitch i thought I got that.

Has to do with signs attached to air i believe.

**Comment by md-5** [comment]
Did they make air return null o.O
I gotta checkout Deadbolt on my new computer

**Comment by daemitus** [comment]
I thought I had an IF for AIR, continue. gotta look again.

**Comment by godsyn** [comment]
Link to my config if it helps: https://github.com/daemitus/Deadbolt/issues/25
 Same CB version as that (fixed) bug, just the new (2.0.6) version of Deadbolt.

**Comment by daemitus** [comment]
```
public static BlockFace getFacingFromByte(byte b) {
    switch (b) {
        case 0x2:
            return BlockFace.EAST;
        case 0x3:
            return BlockFace.WEST;
        case 0x4:
            return BlockFace.NORTH;
        case 0x5:
            return BlockFace.SOUTH;
        default:
            return null;
    }
```

I bet you money, its because its a signpost, not a wallsign. I was checking for instanceof Sign instead of just wallsign.

**Comment by md-5** [comment]
ProTip: instanceof is MUCH more resource intensive than Material ==

**Comment by daemitus** [comment]
Closed pending it shows up again.
