### ISSUE TITLE
Error on disable from Bridge.java

### ISSUE THREAD

**Issue by daemitus** [md-5/Deadbolt#4]
Occasionally, when doing /reload, this will be thrown.

15:29:31 [SEVERE] Error occurred while disabling Lockette v1.0 (Is it up to date
?): com/daemitus/lockette/bridge/Bridge
java.lang.NoClassDefFoundError: com/daemitus/lockette/bridge/Bridge
        at com.daemitus.lockette.Lockette.onDisable(Lockette.java:52)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:128)
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoade
r.java:906)
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManag
er.java:294)
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginMana
ger.java:287)
        at org.bukkit.plugin.SimplePluginManager.clearPlugins(SimplePluginManage
r.java:315)
        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:423)
        at org.bukkit.command.SimpleCommandMap$ReloadCommand.execute(SimpleComma
ndMap.java:281)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:12
9)
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:3
52)
        at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.
java:737)
        at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:701)

```
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:694)
    at net.minecraft.server.Packet3Chat.a(Packet3Chat.java:33)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:89)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:105)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:454)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:363)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
```

Caused by: java.lang.ClassNotFoundException: com.daemitus.lockette.bridge.Bridge

```
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
```

java:36)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.
java:24)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more

**Comment by md-5** [comment]
Taking a quick look now, but it only occurs when you replace the Lockette.jar while the server is running.

**Comment by daemitus** [comment]
Figures too, I do that alot. Drag and drop, /reload, keep on truckin.

**Comment by md-5** [comment]
I think I fixed this. Definately worthy of Lockette 1.1.1 or another release.

**Comment by daemitus** [comment]
Thats the same thing that clear basically does. Ill see what happens over here.
