### ISSUE TITLE
CB update breaks deadbolt.

### ISSUE THREAD

**Issue by godsyn** [md-5/Deadbolt#41]
Just a heads up: craftbukkit builds after 1696 break deadbolt. I've only tested on 1702 before swapping back to 1696.

Issue: Unable to right-click with sign and when manually placing a [private] sign, the following shows in the console.

```
2012-01-08 08:49:17 [SEVERE] Could not pass event SIGN_CHANGE to Deadbolt
java.lang.ClassCastException: org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
        at com.daemitus.deadbolt.events.SignListener.onSignChange(SignListener.java:80)
        at org.bukkit.plugin.java.JavaPluginLoader$36.execute(JavaPluginLoader.java:514)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:1069)
        at net.minecraft.server.Packet130UpdateSign.a(SourceFile:41)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:93)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:527)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
```

I realize there isn't an RB for the above versions, just letting you guys know that it happens with 1702.

**Comment by md-5** [comment]
I shall investigate.

**Comment by md-5** [comment]
Cannot reprodce

**Comment by godsyn** [comment]
Local issue. I believe it was nolagg that caused it. Removed, all better.
Sorry.
