### ISSUE TITLE
Could not pass event REDSTONE_CHANGE to Deadbolt

### ISSUE THREAD

**Issue by lucasdidur** [md-5/Deadbolt#42]
2012-01-11 12:07:07 [SEVERE] Could not pass event REDSTONE_CHANGE to Deadbolt
java.lang.NullPointerException
    at com.daemitus.deadbolt.events.RedstoneListener.onBlockRedstoneChange(RedstoneListener.java:31)
    at org.bukkit.plugin.java.JavaPluginLoader$38.execute(JavaPluginLoader.java:528)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:339)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:114)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:170)
    at net.minecraft.server.BlockRedstoneWire.a(BlockRedstoneWire.java:160)
    at net.minecraft.server.BlockRedstoneWire.g(BlockRedstoneWire.java:45)
    at net.minecraft.server.BlockRedstoneWire.doPhysics(BlockRedstoneWire.java:290)
    at org.getspout.spout.block.mcblock.CustomBlock.doPhysics(CustomBlock.java:216)
    at net.minecraft.server.World.k(World.java:522)
    at net.minecraft.server.World.applyPhysics(World.java:499)
    at net.minecraft.server.BlockPressurePlate.g(BlockPressurePlate.java:141)
    at net.minecraft.server.BlockPressurePlate.a(BlockPressurePlate.java:63)
    at org.getspout.spout.block.mcblock.CustomBlock.a(CustomBlock.java:199)
    at net.minecraft.server.World.a(World.java:2321)
    at net.minecraft.server.World.doTick(World.java:1740)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:514)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by daemitus** [comment]
Spout block again. What in the world is it doing different.

**Comment by lucasdidur** [comment]
different I do not see anything, but is sending messages to the console without stopping when a activates a redstone door.

**Comment by daemitus** [comment]
Post a screenshot of the door layout, if you know which one is doing it. Or is it all doors worldwide?

**Comment by lucasdidur** [comment]
This bug is in everything that uses redstone
