### ISSUE TITLE
Could not pass event org.bukkit.event.entity.EntityChangeBlockEvent to Deadbolt

### ISSUE THREAD

**Issue by KyleBoyer** [md-5/Deadbolt#52]
21:18:34 [SEVERE] Could not pass event org.bukkit.event.entity.EntityChangeBlockEvent to Deadbolt
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1026)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:61)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:460)
    at net.minecraft.server.EntityEnderman.d(EntityEnderman.java:117)
    at net.minecraft.server.EntityLiving.y_(EntityLiving.java:341)
    at net.minecraft.server.EntityMonster.y_(EntityMonster.java:31)
    at net.minecraft.server.World.entityJoinedWorld(World.java:1262)
    at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:110)
    at net.minecraft.server.World.playerJoinedWorld(World.java:1244)
    at net.minecraft.server.World.tickEntities(World.java:1151)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:528)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$103.execute(JavaPluginLoader.java:1024)
    ... 12 more
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityChangeBlockEvent.getEntity()Lorg/bukkit/entity/LivingEntity;
    at com.daemitus.deadbolt.events.EntityListener.onEntityChangeBlock(EntityListener.java:37)
    ... 17 more

**Comment by krosk93** [comment]
This is fixed on latest dev builds.
