### ISSUE TITLE
Timed doors does not work

### ISSUE THREAD

**Issue by oloflarsson** [md-5/Deadbolt#59]
22:20:17 [WARNING] Task of 'Deadbolt' generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to org.bukkit.material.Door
        at com.daemitus.deadbolt.ToggleDoorTask.run(ToggleDoorTask.java:23)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:590)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:508)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by md-5** [comment]
My bad, I already fixed locally

**Comment by Alslinet** [comment]
This one is back in the latest recommended build of craftbukkit
