### ISSUE TITLE
Bridge Unknown Dependency Issue - Bukkit related softdepend/depend conflict

### ISSUE THREAD

**Issue by daemitus** [md-5/Deadbolt#7]
Using depend: SimpleClans causes an UnknownDependencyException.
The bridge for towny has the same syntax, works fine. 
Changing the filename to zDeadboltBridge... fixes it because it loads after simpleclans. the bukkit logic is not working correctly or is it clans related?

**Comment by md-5** [comment]
Full error:
2011-09-03 21:19:19 [SEVERE] Could not load 'plugins\Clans.jar' in folder 'plugins': SimpleClans
org.bukkit.plugin.UnknownDependencyException: SimpleClans
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:143)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:110)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:51)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:133)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)

**Comment by daemitus** [comment]
Bukkit related softdepend and depend conflict error.
Solution:
stop using depend for the time being?

**Comment by md-5** [comment]
Try making it a softdepend for the time being. Itll keep things tidy while still forcing a last load. I am working on permissionsbukkit atm, so might do later.

**Comment by daemitus** [comment]
They are softdepends in the latest push

**Comment by md-5** [comment]
Closed

**Comment by daemitus** [comment]
Well, I still want to make them hard depends eventually

**Comment by md-5** [comment]
mmm but at this stage the issue belongs to bukkit

**Comment by daemitus** [comment]
Correct.
