### ISSUE TITLE
[SEVERE] Could not pass event BlockPlaceEvent to Deadbolt

### ISSUE THREAD

**Issue by catrone3** [md-5/Deadbolt#70]
I have Removed Chestshop to remove this same error with it. however after doing that it shows up with deadbolt. i have no idea what is causing it or how to fix it. i am running tekkit 3.1.2 which is mc 1.2.5 idk what bukkit build it is though.

My plugins are:
AutoCast
BOSEconomy
ButtonPromote
Buycraft
Buyregion
ChatManager
Citizens
craftscripts
essentials
McMMO
multiverse -core,inventories,portals,signportals
PEX
Pluginmetrics
reservations
residence
residencesigns
spamguard 
worldguard
worldedit

**Comment by oloflarsson** [comment]
Please provide the full error stacktrace. Without it we can do nothing.

**Comment by catrone3** [comment]
[SEVERE] Could not pass event BlockPlaceEvent to Deadbolt
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467)
    at railcraft.common.structures.ItemMetalPost.interactWith(ItemMetalPost.java:120)
    at net.minecraft.server.ItemStack.placeItem(ItemStack.java:83)
    at net.minecraft.server.ItemInWorldManager.interact(ItemInWorldManager.java:318)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:647)
    at net.minecraft.server.Packet15Place.handle(SourceFile:39)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:234)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:119)
    at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:83)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:579)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.NullPointerException
    at com.daemitus.deadbolt.events.BlockListener.onBlockPlace(BlockListener.java:51)
    at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
    ... 14 more

**Comment by benji-sws** [comment]
I got his too. Deadbolt needs to release an update for 1.4.6.

**Comment by md-5** [comment]
http://ci.md-5.net/job/Deadbolt/
