### ISSUE TITLE
Error on startup: Unsupported major.minor version

### ISSUE THREAD

**Issue by Inscrutable** [md-5/Deadbolt#9]
Greetz again daemitus. I have been enjoying Deadbolt 1.1 on my server (RB1060 MC1.73 PEx1.13),
but when I tried to upgrade to the 1.2 version I got the big screed of errors below.
(I did try renaming the bridge with the suffix zzz, same error occurs.
Using Latest versions of PEx bridge and LocketteSim so far as I know, 5 days old according to BukkitDev)

2011-09-12 22:17:28 [INFO] This server is running Craftbukkit version git-Bukkit-0.0.0-980-g4ed23b1-b1060jnks (MC: 1.7.3)
2011-09-12 22:17:28 [SEVERE] Could not load 'plugins\Deadbolt.jar' in folder 'plugins': 
java.lang.UnsupportedClassVersionError: com/daemitus/deadbolt/Deadbolt : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:168)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:143)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:110)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:51)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:133)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-09-12 22:17:29 [INFO] [PermissionsEx] sql backend registered!
2011-09-12 22:17:29 [INFO] [PermissionsEx] file backend registered!
2011-09-12 22:17:29 [INFO] [PermissionsEx] PermissionEx plugin initialized.
2011-09-12 22:17:29 [INFO] [PermissionsEx] p2compat backend registered!
2011-09-12 22:17:29 [INFO] [PermissionsCompat] Compatibility Layer Initalized!
2011-09-12 22:17:29 [SEVERE] Could not load 'plugins\DeadBolt_LocketteSim.jar' in folder 'plugins': Deadbolt
org.bukkit.plugin.UnknownDependencyException: Deadbolt
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:143)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:110)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:51)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:133)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
2011-09-12 22:17:29 [SEVERE] Could not load 'plugins\zzzDeadboltBridge_PermissionsEx.jar' in folder 'plugins': 
java.lang.NoClassDefFoundError: com/daemitus/deadbolt/bridge/DeadboltBridge
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:168)
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:213)
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:136)
    at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:143)
    at org.bukkit.craftbukkit.CraftServer.<init>(CraftServer.java:110)
    at net.minecraft.server.ServerConfigurationManager.<init>(ServerConfigurationManager.java:51)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:133)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:337)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
Caused by: java.lang.ClassNotFoundException: com.daemitus.deadbolt.bridge.DeadboltBridge
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:36)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:24)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more
2011-09-12 22:17:29 [INFO] [PermissionsEx] Initializing file backend

**Comment by daemitus** [comment]
that is because I started using Java7. I figured this would start popping up from the userbase since it was just recently released. See if you can get your host to upgrade, otherwise im going to have to not use all the stuff they just added and downgrade :\

**Comment by md-5** [comment]
Unsupported major.minor version 51.0

Exactly that. Java 7 has been out for over a month now, so updates to hosts should start rolling in.

Thought I was going to get here before Daemitus XD

**Comment by Inscrutable** [comment]
Hiya folks. I got my host to upgrade (That would be ME, I run my server on my quad-core i7 desktop). 
Deadbolt starts and runs fine now. I really appreciate the help.
Mind you, Oracle are still calling Java7 a Dev Build...
So I expect there will be a few more issues until Java7 hits mainstream (Java6-v27 is still the default JRE install).

**Comment by daemitus** [comment]
http://blogs.oracle.com/javase/entry/java_7_has_released

Maybe they just lost track of some of their pages. I dunno :p

**Comment by R4Z0R49** [comment]
Will you be staying with Java 7 or is it possible to go back to Java 6? Im still having issues trying to get Java 7 working under Ubuntu (10.10/maverick).

**Comment by R4Z0R49** [comment]
Yea i already did Ubuntu isn't playing nice so i'm stuck on 1.1 until i get more time to try and debug the problem.

Thanks anyway

**Comment by md-5** [comment]
Any chance you havE the exact error message? Bit of Ubuntu fanboy myself. I will try jdk 7 and see if I can get it to work

**Comment by md-5** [comment]
Ooh! Got it working. Download the rpm file from java.net. Then use alien --scripts on it.
Finally run 

# update-alternatives --install "/usr/bin/java" "java"

"/usr/java/default/bin/java" 3

# update-alternatives --install "/usr/bin/javac" "javac"

"/usr/java/default/bin/javac" 3

# update-alternatives --install "/usr/bin/javaws" "javaws"

"/usr/java/default/bin/javaws" 3

Skip javac unless you installed the jdk.

**Comment by R4Z0R49** [comment]
Thanks anyway md-5 my system will not play nice at all with Java 7 and i don't have the time now to debug. Ill stay on 1.1 for as long as my users allow but i know there going to wont fence's so ill end up being forced back to Lockkete/LWC.

Anyhow thanks

**Comment by md-5** [comment]
I will try to go back to java 6 now

**Comment by md-5** [comment]
Got it to work and compile with Java 6, excpet for the moment for some reason doors only open when the bottom half is clicked.

**Comment by md-5** [comment]
O.k all is good. I'm gonna clean some stuff up later today and then release v1.3 compiled with Java6. For now target/ is compiled with 6 though

**Comment by R4Z0R49** [comment]
Your a star nice one.

**Comment by md-5** [comment]
Expect 1.3 from me later today.
